#!/usr/bin/env ruby
#^syntax detection

# Configuration for librarian-puppet.
forge "http://forge.puppetlabs.com"

# mod 'puppetlabs/stdlib'
mod 'puppetlabs/mysql'
mod 'puppetlabs/apache'

# mod 'ntp',
#   :git => 'git://github.com/puppetlabs/puppetlabs-ntp.git'

# mod 'apt',
#   :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
#   :ref => 'feature/master/dans_refactor'
